config/routes.rb
ShowArchive::Application.routes.draw do
  get "attends/new"
  get "welcome/about"
  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'log_in', to: 'sessions#new', as: 'log_in'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :users
  resources :sessions
  resources :attends

  root to: 'welcome#index'

  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :events
end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :user
  has_many :events
  has_many :artists, through: :events
  has_many :venues, through: :events

  attr_accessor :events_attributes

  accepts_nested_attributes_for :artists
  accepts_nested_attributes_for :events
  accepts_nested_attributes_for :venues
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :venues
  has_many :artists
  belongs_to :attend
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :attends
  has_many :events, through: :attends
  has_many :artists, through: :attends
  has_many :venues, through: :attends
  has_secure_password
  validates_uniqueness_of :email


  def venues
    self.events.collect(:venue).uniq
  end

  def artists
    self.events.collect(:artist).uniq
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to log_in_url, alert: "Not authorized" if current_user.nil
  end
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  def new
    @attend = Attend.new
    @event = @attend.events.build
    @artist = @event.artist.build
    @venue = @event.venue.build
  end

  def create
    @attend = current_user.attends.build(attend_params)

    if @attend.save
      session[:user_id] = User.find(session[:user_id])
      redirect_to user_url(current_user), notice: "Attendance added!"
    else
      render "new"
    end
  end

  private

  def attend_params
    params.require(:attend).permit(:rating, :review, :event_id,
      event_attributes: [ :artist_id, :venue_id, :date, :name])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = current_user
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :username, :name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attends/new.html.erb
<h1>Add Attendance</h1>

<%= form_for @attend do |f| %>
  <% if @attend.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @attend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for @event do |event_form| %>
    Event<br />
    <%= event_form.text_field :name %><br />

    <%= event_form.label :date %><br />
    <%= event_form.text_field :date %><br />

    <%= event_form.fields_for @artist do |artist_form| %>
        Artist<br />
        <%= artist_form.text_field :name %><br />
    <% end %>

    <%= event_form.fields_for @venue do |venue_form| %>
        Venue<br />
        <%= venue_form.text_field :name %><br />
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :review %><br />
    <%= f.text_area :review %>
  </div>

  <div class="actions"><%= f.submit "Add Attendance" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShowArchive</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="user_header">
      <% if current_user %>
        Logged in as <%= current_user.username %>.
        <%= link_to "Log Out", log_out_path %>
      <% else %>
      <%= link_to "Sign Up", sign_up_path %> or
      <%= link_to "Log In", log_in_path %> 
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
show<br>
<%= link_to "New Attendance", attends_new_path %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>